nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php-fpm"
    volumes:
      - ~/opt:/opt

php-fpm:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/opt:/opt
php-cli:
    build: ./php
    working_dir: /php-cli
    tty: true
    stdin_open: true
    command: '/bin/bash'
    tty: true
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: yii2-starter-kit
      MYSQL_USER: ysk_dbu
      MYSQL_PASSWORD: ysk_pass

redis:
    build: ./redis
    ports:
      - "6379:6379"
