nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - "php-fpm"
      - "node"
    volumes:
      - ./opt/htdocs:/opt
      - ./opt/log/nginx:/log
      - ./docker/nginx/vhost:/etc/nginx/conf.d

php-fpm:
    build: ./docker/php
    expose:
      - 9000
    links:
      - "mysql"
      - "redis"
    volumes:
      - ./opt/htdocs:/opt
php-cli:
    build: ./docker/php
    working_dir: /opt
    tty: true
    stdin_open: true
    command: '/bin/bash'
    tty: true
    links:
      - "mysql"
      - "redis"
    volumes:
      - ./opt/htdocs:/opt

mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbname 
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

redis:
    build: ./docker/redis
    ports:
      - "6379:6379"

node:
    build: ./docker/node
    ports:
      - "3000:3000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ./opt/htdocs/node:/usr/src/app 
